name: Unzip file

on:
  push:
    paths:
      - '**.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unzip the file
        run: |
          unzip *.zip -d unzipped
      - name: Commit unzipped files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add unzipped/
          git commit -m "Unzipped contents"
          git push
